name: 'Test Plugins'

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  schedule:
    - cron: 17 0 * * *

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: 'Prepare'
        shell: bash
        id: prep
        run: |
          : Prepare
          set -e
          if ${{ runner.os == 'Linux' }}; then
            plugins_str="$(tr '\n' ' ' < ./plugins-ubuntu.txt)"
          else
            plugins_str="$(tr '\n' ' ' < ./plugins.txt)"
          fi
          echo "plugins=${plugins_str}" >> $GITHUB_OUTPUT

      - name: 'Install npcap on Windows'
        if: runner.os == 'Windows'
        shell: bash
        run: |
          : npcap
          set -e
          mkdir /tmp/npcap
          cd /tmp/npcap
          curl -O https://www.nagater.net/obs-studio/npcap-1.87.zip
          unzip npcap-1.87.zip
          mv *.dll 'C:/windows/system32/'

      - name: 'Setup onsdriver'
        uses: noris-plugins-for-obs/onsdriver@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          first-time-log: ./logs/
          graphics-size: 640x360
          obs-architecture: ${{ matrix.arch }}
          obs-plugins: |
            ${{ steps.prep.outputs.plugins }}
          include-prerelease: true

      - name: 'Install required libraries'
        run: |
          python -m pip install -r requirements.txt

      - name: 'Test with onsdriver'
        run: |
          python -m unittest discover test-plugins/

      - name: 'Upload logs of onsdriver'
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-${{ matrix.os }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: |
            logs/*
